{% set name = "hashids" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hashids-{{ version }}.tar.gz
  sha256: 6c3dc775e65efc2ce2c157a65acb776d634cb814598f406469abef00ae3f635c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core >=2,<4
  run:
    - python >={{ python_min }}

test:
  imports:
    - hashids
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://hashids.org/python/
  summary: Implements the hashids algorithm in python. For more information, visit http://hashids.org/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xmnlab
